backend:
  name: git-gateway
  branch: main
local_backend: true
media_folder: "/src/assets/images"
public_folder: "/src/assets/images"

collections:
  - name: "tracks" # Used in routes, e.g., /admin/collections/blog
    label: "Tracks" # Used in the UI
    folder: "src/content/tracks" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{fields.name}}"
    fields: # The fields for each document, usually in frontmatter
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Color", name: "color", widget: "select", options: ["yellow","red","light-blue","purple","cyan"] }
  - name: "speakers"
    label: "Speakers"
    folder: "src/content/speakers"
    create: true
    slug: "{{fields.name}}"
    fields:
      - { label: "Name", name: "name", widget: "string"}
      - { label: "Role", name: "role", widget: "string"}
      - { label: "Company", name: "company", widget: "string"}
      - { label: "Avatar", name: "avatar", widget: "image"}
      - { label: "Bio", name: "bio", widget: "text"}
      - { label: "Featured", name: "featured", widget: "boolean", default: false}
      - { label: "Color", name: "color", widget: "select", options: ["yellow","red","light-blue","purple","cyan"] }
