backend:
  name: git-gateway
  branch: main
local_backend: true
media_folder: "/src/assets/images"
public_folder: "/src/assets/images"

collections:
  - name: "tracks" # Used in routes, e.g., /admin/collections/blog
    label: "Tracks" # Used in the UI
    folder: "src/content/tracks" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{fields.name}}"
    fields: # The fields for each document, usually in frontmatter
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Color", name: "color", widget: "select", options: ["yellow","red","light-blue","purple","cyan"] }
  - name: "speakers"
    label: "Speakers"
    folder: "src/content/speakers"
    create: true
    slug: "{{fields.name}}"
    fields:
      - { label: "Name", name: "name", widget: "string"}
      - { label: "Role", name: "role", widget: "string"}
      - { label: "Company", name: "company", widget: "string"}
      - { label: "Avatar", name: "avatar", widget: "image"}
      - { label: "Bio", name: "bio", widget: "text"}
      - { label: "Featured", name: "featured", widget: "boolean", default: false}
      - { label: "Color", name: "color", widget: "select", options: ["yellow","red","light-blue","purple","cyan"] }
  - name: "talks"
    label: "Talks"
    folder: "src/content/talks"
    create: true
    slug: "{{fields.title}}"
    fields:
      - { label: "Title", name: "title", widget: "string"}
      - { label: "Speaker", name: "speaker", widget: "relation", collection: "speakers", search_fields: ["name"], value_field: "name", display_fields: ["name"] }
      - { label: "Track", name: "track", widget: "relation", collection: "tracks", search_fields: ["name"], value_field: "name", display_fields: ["name"]}
      - { label: "Description", name: "description", widget: "text"}
      - { label: "Day", name: "day", widget: "number", min: 1, max: 3, step: 1, value_type: "int", default: 1}
      - { label: "Start Time", name: "startTime", widget: "datetime", time_format: "HH:mm"}
      - { label: "End Time", name: "endTime", widget: "datetime", time_format: "HH:mm"}
      - { label: "Location", name: "location", widget: "string"}
      - { label: "Highlighted", name: "highlighted", widget: "boolean", default: false}